services:
  webapp:
    image: php:8.1.0-apache
    ports:
    - ${PHP_PORT:-8000}:80
    volumes:
    - ${PHP_APP:-./php/src}:/var/www/html:ro

  database:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=value